import { defineCopy } from "./language";

export const PREPARE_COPY = defineCopy("prepare-flow", {
  es: {
    steps: ["Negocio", "Actividad", "Servicios", "Horario", "Revisar"],
    titles: [
      "Tu negocio",
      "¿Qué servicios ofreces?",
      "Tus servicios",
      "Tu horario",
      "Revisa tu negocio",
    ],
    subtitles: [
      "Dónde trabajas y cómo contactarte.",
      "Elige una o varias especialidades.",
      "",
      "Los horarios en los que aceptas citas.",
      "Revisa los datos antes de empezar.",
    ],
    next: "Continuar",
    categoryLabels: [
      "Manicure",
      "Pedicure",
      "Pestañas",
      "Cejas",
      "Faciales",
      "Cabello",
      "Masajes",
      "Maquillaje permanente",
    ],
    categoryHint: "",
    categoryError: "Elige al menos una especialidad.",
    changeCategories: "Especialidades",
    category: "Especialidad",
    back: "Volver",
    backToReview: "Volver a revisar",
    save: "Guardar y empezar",
    saving: "Guardando tu negocio…",
    savingHint: "Estamos comprobando cada cambio antes de abrir tu agenda. Mantén esta pestaña abierta.",
    savingSteps: [
      "Guardando los datos del negocio…",
      "Creando servicios y precios…",
      "Preparando el calendario…",
      "Confirmando el horario…",
      "Configurando las condiciones…",
      "Comprobando que todo esté listo…",
    ],
    name: "Nombre del negocio",
    country: "País",
    city: "Ciudad",
    zone: "Zona horaria",
    now: "Hora local",
    phone: "Teléfono de contacto",
    phonePrefix: "Código de país del teléfono",
    address: "Dirección o zona de atención",
    addressPlaceholder: "Empieza a escribir una dirección",
    optional: "Opcional",
    addressHint:
      "Busca tu dirección, colonia o zona.",
    solo: "Solo yo",
    team: "Con más profesionales",
    owner: "Yo también atiendo",
    member: "Nombre",
    addMember: "Agregar persona",
    tier: "Precios sugeridos",
    budget: "Económico",
    standard: "Estándar",
    premium: "Premium",
    suggestion: "Precios de referencia. Ajústalos a tu negocio.",
    custom: "Tu precio",
    currencyReview: "Revisa el precio en la nueva moneda",
    service: "Servicio",
    price: "Precio",
    duration: "Duración (min)",
    add: "Agregar servicio",
    edit: "Editar",
    remove: "Eliminar",
    cancel: "Cancelar",
    done: "Guardar",
    import: "Subir mi lista",
    upload: "Subir",
    uploadTitle: "¿Tienes tu lista de precios?",
    uploadHint: "Sube una foto o PDF y la ponemos aquí",
    readingList: "Leyendo tu lista…",
    importedSummary: "Lista importada · {count} servicios",
    importChoiceHint: "¿Qué hacemos con tu lista actual?",
    editedPricesStay: "Los precios que editaste a mano no se tocan.",
    text: "Pegar texto",
    camera: "Tomar foto",
    photos: "Elegir foto",
    document: "PDF o archivo",
    assistant: "Ayudarme a ajustar",
    assistantHint: "Ej.: sube un 10% estos precios y deja manicure en 30.",
    assistantRead: "Preparar cambios",
    filePrivacy: "La foto o el archivo se envía a Chatfuel para leerlo. Revisarás los datos antes de aplicarlos.",
    missingValues: "Completa los precios, moneda o minutos que no aparecen en el archivo.",
    importUnavailable: "No pudimos leerlo ahora. Prueba con otra foto, captura o PDF.",
    photoLarge: "Elige una foto de menos de 20 MB o un PDF de menos de 2,5 MB.",
    photoFailed: "No pudimos abrir esa imagen. Prueba con una captura de pantalla o un PDF.",
    file: "Elegir archivo CSV",
    importTitle: "Tu lista de precios",
    textLabel: "Servicios, precios y duración",
    textPlaceholder: "Servicio, Precio, Minutos\nManicure, 25, 60",
    read: "Leer lista",
    reading: "Leyendo…",
    importReview: "Revisa los servicios",
    selected: "Aplicar seleccionados",
    chooseAnother: "Elegir otro archivo",
    importReplaceSummary: "Encontramos {count} servicios.",
    replaceServices: "Reemplazar la lista",
    addImportedServices: "Agregar a la actual",
    undo: "Deshacer",
    fromList: "De tu lista",
    replacement: "Reemplaza un servicio existente",
    noRows:
      "No encontramos servicios con precio y duración. Puedes corregir el texto o agregarlos manualmente.",
    rejected: "Algunas filas no tienen precio o duración y no se incluirán.",
    fileError: "No pudimos leer el archivo. Usa un CSV o pega el texto.",
    fileLarge: "El archivo debe pesar menos de 2 MB.",
    importEmpty: "Selecciona al menos un servicio.",
    duplicateService:
      "Hay dos servicios con el mismo nombre. Cambia uno o desmárcalo.",
    copyHours: "Aplicar el horario del lunes a todos los días abiertos",
    copiedHours: "Horario aplicado",
    copyFrom: "Copiar horario de",
    closed: "Cerrado",
    days: ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
    hours: "Horario",
    people: "Equipo",
    allServices: "Servicios que realiza",
    rules: "Condiciones de las citas",
    deposit: "Solicitar anticipo al reservar",
    depositAmount: "Importe del anticipo",
    depositHint:
      "El asistente informará el importe. El cobro y su comprobación son manuales.",
    noDeposit: "Sin pago anticipado",
    notice: "Aviso para cancelar",
    hourUnit: "horas",
    noNotice: "Sin aviso mínimo",
    assistantLanguage: "Idioma de atención",
    spanish: "Español",
    english: "Inglés",
    required: "Completa este campo.",
    phoneError: "Revisa el número y el código de país.",
    zoneError: "Elige la zona horaria de tu negocio.",
    serviceError: "Revisa el nombre, precio y duración del servicio.",
    hoursError:
      "Elige al menos un día y una hora de cierre posterior a la apertura.",
    teamError: "Revisa el nombre del propietario y sus servicios.",
    depositError: "Revisa el importe del abono en la moneda de tu negocio.",
    failed:
      "No pudimos guardar todos los datos. Tu borrador sigue aquí; vuelve a intentarlo.",
    retryLoad: "Volver a cargar",
    loadError: "No pudimos cargar los datos de tu negocio.",
    loading: "Cargando tu negocio…",
    draft: "Borrador",
    noLive:
      "Al guardar se configurarán tu calendario y tus servicios. Instagram seguirá apagado.",
    ready: "Tu agenda está lista",
    readySub: "Ya puedes crear tu primera cita.",
    changedElsewhere: "El borrador cambió en otra ventana. Vuelve a cargar para revisar la última versión.",
    agenda: "Abrir mi calendario",
    instagram: "Conectar Instagram",
    later: "Puedes conectarlo más adelante.",
    servicesUnit: "servicios",
    peopleUnit: "personas",
    reviewBusiness: "Negocio",
    reviewServices: "Servicios y precios",
    reviewSchedule: "Horario y condiciones",
  },
  en: {
    steps: ["Business", "Specialties", "Services", "Hours", "Review"],
    titles: [
      "Your business",
      "What do you offer?",
      "Your services",
      "Your hours",
      "Review your business",
    ],
    subtitles: [
      "Where you work and how to reach you.",
      "Choose one or more specialties.",
      "",
      "The hours when you accept appointments.",
      "Review your details before getting started.",
    ],
    next: "Continue",
    categoryLabels: [
      "Manicure",
      "Pedicure",
      "Lashes",
      "Brows",
      "Facials",
      "Hair",
      "Massage",
      "Permanent makeup",
    ],
    categoryHint: "",
    categoryError: "Choose at least one specialty.",
    changeCategories: "Specialties",
    category: "Specialty",
    back: "Back",
    backToReview: "Back to review",
    save: "Save and get started",
    saving: "Saving your business…",
    savingHint: "We are checking each change before opening your calendar. Keep this tab open.",
    savingSteps: [
      "Saving business details…",
      "Creating services and prices…",
      "Preparing the calendar…",
      "Confirming business hours…",
      "Setting appointment policies…",
      "Checking everything is ready…",
    ],
    name: "Business name",
    country: "Country",
    city: "City",
    zone: "Time zone",
    now: "Local time",
    phone: "Contact phone",
    phonePrefix: "Phone country code",
    address: "Address or service area",
    addressPlaceholder: "Start typing an address",
    optional: "Optional",
    addressHint:
      "Search for your address, neighborhood, or service area.",
    solo: "Just me",
    team: "With other professionals",
    owner: "I also serve clients",
    member: "Name",
    addMember: "Add person",
    tier: "Suggested prices",
    budget: "Budget",
    standard: "Standard",
    premium: "Premium",
    suggestion: "Starting prices. Adjust them for your business.",
    custom: "Your price",
    currencyReview: "Review this price in the new currency",
    service: "Service",
    price: "Price",
    duration: "Duration (min)",
    add: "Add service",
    edit: "Edit",
    remove: "Remove",
    cancel: "Cancel",
    done: "Save",
    import: "Upload my list",
    upload: "Upload",
    uploadTitle: "Have a price list?",
    uploadHint: "Upload a photo or PDF and we will put it here",
    readingList: "Reading your list…",
    importedSummary: "List imported · {count} services",
    importChoiceHint: "What should we do with your current list?",
    editedPricesStay: "Prices you edited by hand stay unchanged.",
    text: "Paste text",
    camera: "Take photo",
    photos: "Choose photo",
    document: "PDF or file",
    assistant: "Help me adjust prices",
    assistantHint: "E.g. raise these prices by 10% and keep manicure at 30.",
    assistantRead: "Prepare changes",
    filePrivacy: "Your photo or file is sent to Chatfuel to read. Review the details before applying them.",
    missingValues: "Fill in any prices, currency or minutes missing from the file.",
    importUnavailable: "We could not read it right now. Try another photo, screenshot, or PDF.",
    photoLarge: "Choose a photo under 20 MB or a PDF under 2.5 MB.",
    photoFailed: "We could not open this image. Try a screenshot or a PDF.",
    file: "Choose CSV file",
    importTitle: "Your price list",
    textLabel: "Services, prices and duration",
    textPlaceholder: "Service, Price, Minutes\nManicure, 25, 60",
    read: "Read list",
    reading: "Reading…",
    importReview: "Review services",
    selected: "Apply selected",
    chooseAnother: "Choose another file",
    importReplaceSummary: "We found {count} services.",
    replaceServices: "Replace the list",
    addImportedServices: "Add to current list",
    undo: "Undo",
    fromList: "From your list",
    replacement: "Replaces an existing service",
    noRows:
      "No services with both price and duration were found. Edit the text or add services manually.",
    rejected:
      "Some rows are missing a price or duration and will not be included.",
    fileError: "We could not read that file. Use a CSV or paste the text.",
    fileLarge: "The file must be smaller than 2 MB.",
    importEmpty: "Select at least one service.",
    duplicateService:
      "Two services have the same name. Rename one or deselect it.",
    copyHours: "Apply Monday's hours to every open day",
    copiedHours: "Hours applied",
    copyFrom: "Copy hours from",
    closed: "Closed",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    hours: "Hours",
    people: "Team",
    allServices: "Services they perform",
    rules: "Appointment policies",
    deposit: "Request a deposit when booking",
    depositAmount: "Deposit amount",
    depositHint:
      "The assistant tells the client the amount. Collection and verification are manual.",
    noDeposit: "No deposit",
    notice: "Cancellation notice",
    hourUnit: "hours",
    noNotice: "No minimum notice",
    assistantLanguage: "Client language",
    spanish: "Spanish",
    english: "English",
    required: "Fill in this field.",
    phoneError: "Check the phone number and country code.",
    zoneError: "Choose your business time zone.",
    serviceError: "Check the service name, price, and duration.",
    hoursError: "Choose an open day and a closing time after opening.",
    teamError: "Review the owner's name and services.",
    depositError: "Review the deposit amount in your business currency.",
    failed:
      "We could not save all your details. Your draft is still here; please try again.",
    retryLoad: "Reload",
    loadError: "We could not load your business details.",
    loading: "Loading your business…",
    draft: "Draft",
    noLive:
      "Saving sets up your calendar and services. Instagram will stay off.",
    ready: "Your calendar is ready",
    readySub: "You can now add your first appointment.",
    changedElsewhere: "The draft changed in another window. Reload to review the latest version.",
    agenda: "Open my calendar",
    instagram: "Connect Instagram",
    later: "You can connect it later.",
    servicesUnit: "services",
    peopleUnit: "people",
    reviewBusiness: "Business",
    reviewServices: "Services and prices",
    reviewSchedule: "Hours and policies",
  },
  pt: {
    steps: ["Negócio", "Atividade", "Serviços", "Horários", "Revisão"],
    titles: [
      "Seu negócio",
      "Quais serviços você oferece?",
      "Seus serviços",
      "Seus horários",
      "Revise seu negócio",
    ],
    subtitles: [
      "Onde você atende e como entrar em contato.",
      "Escolha uma ou mais especialidades.",
      "",
      "Os horários em que você aceita agendamentos.",
      "Confira os dados antes de começar.",
    ],
    next: "Continuar",
    categoryLabels: [
      "Manicure", "Pedicure", "Cílios", "Sobrancelhas", "Estética facial",
      "Cabelo", "Massagem", "Maquiagem definitiva",
    ],
    categoryHint: "",
    categoryError: "Escolha pelo menos uma especialidade.",
    changeCategories: "Especialidades",
    category: "Especialidade",
    back: "Voltar",
    backToReview: "Voltar para a revisão",
    save: "Salvar e começar",
    saving: "Salvando seu negócio…",
    savingHint: "Estamos verificando cada alteração antes de abrir sua agenda. Mantenha esta aba aberta.",
    savingSteps: [
      "Salvando os dados do negócio…",
      "Criando serviços e preços…",
      "Preparando a agenda…",
      "Confirmando os horários…",
      "Configurando as condições…",
      "Verificando se está tudo pronto…",
    ],
    name: "Nome do negócio",
    country: "País",
    city: "Cidade",
    zone: "Fuso horário",
    now: "Hora local",
    phone: "Telefone de contato",
    phonePrefix: "Código do país do telefone",
    address: "Endereço ou região de atendimento",
    addressPlaceholder: "Comece a digitar um endereço",
    optional: "Opcional",
    addressHint: "Busque seu endereço, bairro ou região de atendimento.",
    solo: "Só eu",
    team: "Com outros profissionais",
    owner: "Eu também atendo",
    member: "Nome",
    addMember: "Adicionar pessoa",
    tier: "Preços sugeridos",
    budget: "Econômico",
    standard: "Padrão",
    premium: "Premium",
    suggestion: "Preços de referência. Ajuste-os ao seu negócio.",
    custom: "Seu preço",
    currencyReview: "Confira o preço na nova moeda",
    service: "Serviço",
    price: "Preço",
    duration: "Duração (min)",
    add: "Adicionar serviço",
    edit: "Editar",
    remove: "Excluir",
    cancel: "Cancelar",
    done: "Salvar",
    import: "Enviar minha lista",
    upload: "Enviar",
    uploadTitle: "Você tem uma lista de preços?",
    uploadHint: "Envie uma foto ou PDF e colocamos tudo aqui",
    readingList: "Lendo sua lista…",
    importedSummary: "Lista importada · {count} serviços",
    importChoiceHint: "O que devemos fazer com sua lista atual?",
    editedPricesStay: "Os preços que você editou à mão não serão alterados.",
    text: "Colar texto",
    camera: "Tirar foto",
    photos: "Escolher foto",
    document: "PDF ou arquivo",
    assistant: "Ajude-me a ajustar",
    assistantHint: "Ex.: aumente estes preços em 10% e mantenha manicure em 30.",
    assistantRead: "Preparar alterações",
    filePrivacy: "A foto ou o arquivo é enviado ao Chatfuel para leitura. Você revisará os dados antes de aplicá-los.",
    missingValues: "Preencha os preços, a moeda ou os minutos que faltarem no arquivo.",
    importUnavailable: "Não foi possível ler agora. Tente outra foto, captura de tela ou PDF.",
    photoLarge: "Escolha uma foto com menos de 20 MB ou um PDF com menos de 2,5 MB.",
    photoFailed: "Não foi possível abrir essa imagem. Tente uma captura de tela ou um PDF.",
    file: "Escolher arquivo CSV",
    importTitle: "Sua lista de preços",
    textLabel: "Serviços, preços e duração",
    textPlaceholder: "Serviço, Preço, Minutos\nManicure, 25, 60",
    read: "Ler lista",
    reading: "Lendo…",
    importReview: "Revise os serviços",
    selected: "Aplicar selecionados",
    chooseAnother: "Escolher outro arquivo",
    importReplaceSummary: "Encontramos {count} serviços.",
    replaceServices: "Substituir a lista",
    addImportedServices: "Adicionar à lista atual",
    undo: "Desfazer",
    fromList: "Da sua lista",
    replacement: "Substitui um serviço existente",
    noRows: "Não encontramos serviços com preço e duração. Corrija o texto ou adicione-os manualmente.",
    rejected: "Algumas linhas não têm preço ou duração e não serão incluídas.",
    fileError: "Não foi possível ler o arquivo. Use um CSV ou cole o texto.",
    fileLarge: "O arquivo deve ter menos de 2 MB.",
    importEmpty: "Selecione pelo menos um serviço.",
    duplicateService: "Há dois serviços com o mesmo nome. Renomeie um deles ou desmarque-o.",
    copyHours: "Aplicar o horário de segunda-feira a todos os dias abertos",
    copiedHours: "Horário aplicado",
    copyFrom: "Copiar horário de",
    closed: "Fechado",
    days: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
    hours: "Horários",
    people: "Equipe",
    allServices: "Serviços que realiza",
    rules: "Condições dos agendamentos",
    deposit: "Pedir sinal ao agendar",
    depositAmount: "Valor do sinal",
    depositHint: "O assistente informa o valor. O recebimento e a conferência são manuais.",
    noDeposit: "Sem sinal",
    notice: "Antecedência para cancelar",
    hourUnit: "horas",
    noNotice: "Sem antecedência mínima",
    assistantLanguage: "Idioma de atendimento",
    spanish: "Espanhol",
    english: "Inglês",
    required: "Preencha este campo.",
    phoneError: "Confira o número de telefone e o código do país.",
    zoneError: "Escolha o fuso horário do seu negócio.",
    serviceError: "Confira o nome, o preço e a duração do serviço.",
    hoursError: "Escolha pelo menos um dia e um horário de fechamento posterior ao de abertura.",
    teamError: "Confira o nome do proprietário e os serviços que realiza.",
    depositError: "Confira o valor do sinal na moeda do seu negócio.",
    failed: "Não foi possível salvar todos os dados. Seu rascunho continua aqui; tente novamente.",
    retryLoad: "Carregar novamente",
    loadError: "Não foi possível carregar os dados do seu negócio.",
    loading: "Carregando seu negócio…",
    draft: "Rascunho",
    noLive: "Ao salvar, sua agenda e seus serviços serão configurados. O Instagram continuará desligado.",
    ready: "Sua agenda está pronta",
    readySub: "Você já pode criar seu primeiro agendamento.",
    changedElsewhere: "O rascunho foi alterado em outra janela. Recarregue para ver a versão mais recente.",
    agenda: "Abrir minha agenda",
    instagram: "Conectar Instagram",
    later: "Você pode conectá-lo mais tarde.",
    servicesUnit: "serviços",
    peopleUnit: "pessoas",
    reviewBusiness: "Negócio",
    reviewServices: "Serviços e preços",
    reviewSchedule: "Horários e condições",
  },
});
