import { defineCopy } from "./language";

export const EQUIPO_COPY = defineCopy("accesos", {
  es: {
    title: "Accesos del equipo",
    lead: "Una gerente maneja todo el salón. Una especialista ve solo su propia agenda.",
    staff: "Con acceso",
    invites: "Invitaciones pendientes",
    noInvites: "No hay invitaciones pendientes.",
    invite: "Invitar a alguien",
    name: "Nombre",
    email: "Correo",
    level: "Nivel de acceso",
    manager: "Gerente",
    specialist: "Especialista",
    managerHint: "Todo el salón: agenda, catálogo, ajustes y el asistente.",
    specialistHint: "Solo su agenda: sus citas, sus clientas.",
    whichSpecialist: "¿Quién es en la agenda?",
    pickSpecialist: "Elige una profesional…",
    send: "Enviar invitación",
    sending: "Enviando…",
    sent: (email: string) => `Invitación enviada a ${email}.`,
    owner: "Dueña",
    noSpecialist: "Sin agenda asignada",
    unlinked: "Sin asignar",
    revoke: "Cancelar",
    revoked: "Invitación cancelada.",
    remove: "Quitar acceso",
    removeWhat: "Acceso",
    removed: "Acceso retirado.",
    saved: "Listo.",
    loadFailed: "No se pudo leer el equipo.",
    needSpecialist: "Elige a qué profesional corresponde.",
    needEmail: "Escribe un correo válido.",
    missingSpecialist: "Su agenda ya no existe",
    pickFirst: "Elige su agenda para dejarla como especialista.",
    managersOnly: "Solo una gerente administra los accesos del equipo.",
    notSent: "No hay correo configurado: pásale este enlace.",
    status: { pending: "pendiente", accepted: "aceptada", revoked: "cancelada", expired: "vencida" },
  },
  en: {
    title: "Team access",
    lead: "A manager runs the whole salon. A specialist sees only her own calendar.",
    staff: "With access",
    invites: "Pending invitations",
    noInvites: "No pending invitations.",
    invite: "Invite someone",
    name: "Name",
    email: "Email",
    level: "Access level",
    manager: "Manager",
    specialist: "Specialist",
    managerHint: "The whole salon: calendar, catalog, settings and the assistant.",
    specialistHint: "Her calendar only: her appointments, her clients.",
    whichSpecialist: "Who is she in the calendar?",
    pickSpecialist: "Choose a professional…",
    send: "Send invitation",
    sending: "Sending…",
    sent: (email: string) => `Invitation sent to ${email}.`,
    owner: "Owner",
    noSpecialist: "No calendar linked",
    unlinked: "Not linked",
    revoke: "Cancel",
    revoked: "Invitation cancelled.",
    remove: "Remove access",
    removeWhat: "Access",
    removed: "Access removed.",
    saved: "Done.",
    loadFailed: "The team could not be read.",
    needSpecialist: "Choose which professional she is.",
    needEmail: "Enter a valid email.",
    missingSpecialist: "Her calendar no longer exists",
    pickFirst: "Choose her calendar to make her a specialist.",
    managersOnly: "Only a manager administers team access.",
    notSent: "No mail is configured: hand her this link.",
    status: { pending: "pending", accepted: "accepted", revoked: "cancelled", expired: "expired" },
  },
  pt: {
    title: "Acessos da equipe",
    lead: "Uma gerente cuida do salão inteiro. Uma especialista vê apenas a própria agenda.",
    staff: "Com acesso",
    invites: "Convites pendentes",
    noInvites: "Nenhum convite pendente.",
    invite: "Convidar alguém",
    name: "Nome",
    email: "E-mail",
    level: "Nível de acesso",
    manager: "Gerente",
    specialist: "Especialista",
    managerHint: "O salão inteiro: agenda, catálogo, ajustes e o assistente.",
    specialistHint: "Só a agenda dela: seus atendimentos, suas clientes.",
    whichSpecialist: "Quem ela é na agenda?",
    pickSpecialist: "Escolha uma profissional…",
    send: "Enviar convite",
    sending: "Enviando…",
    sent: (email: string) => `Convite enviado para ${email}.`,
    owner: "Proprietária",
    noSpecialist: "Sem agenda vinculada",
    unlinked: "Não vinculada",
    revoke: "Cancelar",
    revoked: "Convite cancelado.",
    remove: "Remover acesso",
    removeWhat: "Acesso",
    removed: "Acesso removido.",
    saved: "Pronto.",
    loadFailed: "Não foi possível ler a equipe.",
    needSpecialist: "Escolha a qual profissional ela corresponde.",
    needEmail: "Digite um e-mail válido.",
    missingSpecialist: "A agenda dela não existe mais",
    pickFirst: "Escolha a agenda dela para deixá-la como especialista.",
    managersOnly: "Só uma gerente administra os acessos da equipe.",
    notSent: "Sem e-mail configurado: passe este link para ela.",
    status: { pending: "pendente", accepted: "aceito", revoked: "cancelado", expired: "expirado" },
  },
});

