import { defineCopy } from "./lib/language";

const es = {
  title: "Comment Studio",
  subtitle: "Cada comentario con intención de compra recibe un Direct con tus precios. Sin IA, sin costo por uso.",
  language: "Idioma",
  loading: "Leyendo tu bot…",
  loadFailed: "No se pudieron leer las automatizaciones.",
  retry: "Reintentar",
  status: {
    loading: "…",
    running: "Activo",
    off: "Apagado",
    drifted: "Necesita reparación",
    aiBooking: "Asistente con IA activo",
  },
  statusHint: {
    running: "Responde los comentarios con tus palabras y manda el Direct.",
    off: "Todavía no responde comentarios. Revisa los textos y enciéndelo.",
    drifted: "Alguien cambió las automatizaciones a mano. Repáralo con un toque.",
    aiBooking: "El asistente con IA lleva el Direct. Pasar a Comment Studio lo apaga y deja solo respuestas fijas.",
  },
  instagram: {
    missing: "Conecta tu Instagram",
    missingHint: "Comment Studio responde en la cuenta que conectes en Canales.",
    connect: "Ir a Canales",
    connected: (handle: string) => `Responde en @${handle}`,
  },
  facts: {
    unavailable: "No se pudieron leer tus servicios y horarios; los textos sugeridos son genéricos.",
  },
  posts: {
    title: "Publicaciones",
    description: "Dónde escucha los comentarios.",
    all: "Todas las publicaciones.",
    selectedHint: (n: number) => (n === 1 ? "Solo 1 publicación elegida." : `Solo ${n} publicaciones elegidas.`),
    pick: "Para elegir publicaciones concretas, abre la regla “Comment Studio · preguntas de precio y hora” en Automatizaciones.",
    open: "Abrir Automatizaciones",
  },
  keywords: {
    title: "Palabras",
    description: "Responde solo si el comentario contiene alguna de estas palabras.",
    placeholder: "Escribe una palabra y Enter",
    reset: "Volver a las sugeridas",
    count: (n: number, max: number) => `${n} de ${max}`,
    rejected: {
      empty: "Escribe algo.",
      tooLong: "Máximo 50 caracteres por palabra.",
      duplicate: "Esa palabra ya está.",
      tooMany: "Máximo 50 palabras.",
    },
  },
  publicReply: {
    title: "Respuesta pública",
    description: "Lo que ve todo el mundo debajo del comentario.",
    switch: "Responder en público",
  },
  direct: {
    title: "Direct",
    description: "El mensaje privado que recibe quien comentó. Se arma con tus servicios y precios de la base de conocimiento; edítalo si quieres.",
    useGenerated: "Usar el texto sugerido",
  },
  problems: {
    posts: "La regla tiene publicaciones elegidas pero la lista está vacía: revísala en Automatizaciones.",
    keywords: "Agrega al menos una palabra.",
    public: "Escribe la respuesta pública o apágala.",
    direct: "Escribe el mensaje del Direct.",
  },
  action: {
    turnOn: "Encender",
    save: "Guardar cambios",
    repair: "Reparar",
    switch: "Pasar a Comment Studio",
    working: "Guardando…",
  },
  toast: {
    saved: "Listo: Comment Studio está activo.",
    failed: "No se pudo guardar.",
    readback: "Se guardó, pero el bot no quedó como se esperaba. Revisa Automatizaciones.",
  },
  errors: {
    InstagramNotConnected: "Conecta tu Instagram en Canales y vuelve a intentar.",
    InstagramDoesNotConnected: "Conecta tu Instagram en Canales y vuelve a intentar.",
    FuelyListOfPostsNoConnectedAccount: "Conecta tu Instagram en Canales y vuelve a intentar.",
    FuelyAutomationBeingEdited: "Alguien está editando las automatizaciones ahora mismo. Espera un momento y reintenta.",
    FuelyAutomationScopeLimitReached: "Este bot ya tiene el máximo de reglas para comentarios. Borra una en Automatizaciones.",
    FuelyKeywordsTooMany: "Demasiadas palabras: deja 50 como máximo.",
    FuelyKeywordTooLong: "Una palabra supera los 50 caracteres.",
  } as Record<string, string>,
};

export type ScreenCopy = typeof es;

export const SCREEN = defineCopy<ScreenCopy>("comment-studio.screen", {
  es,
  en: {
    title: "Comment Studio",
    subtitle: "Every comment with buying intent gets a Direct with your prices. No AI, no usage cost.",
    language: "Language",
    loading: "Reading your bot…",
    loadFailed: "The automations could not be read.",
    retry: "Try again",
    status: { loading: "…", running: "On", off: "Off", drifted: "Needs repair", aiBooking: "AI assistant is on" },
    statusHint: {
      running: "Answers comments with your words and sends the Direct.",
      off: "Not answering comments yet. Check the texts and turn it on.",
      drifted: "Someone changed the automations by hand. Repair it with one tap.",
      aiBooking: "The AI assistant runs your Direct. Switching to Comment Studio turns it off and leaves fixed replies only.",
    },
    instagram: {
      missing: "Connect your Instagram",
      missingHint: "Comment Studio answers on the account you connect in Channels.",
      connect: "Go to Channels",
      connected: (handle: string) => `Answering on @${handle}`,
    },
    facts: {
      unavailable: "Your services and hours could not be read; the suggested texts are generic.",
    },
    posts: {
      title: "Posts",
      description: "Where it listens for comments.",
      all: "All posts.",
      selectedHint: (n: number) => (n === 1 ? "Only 1 post chosen." : `Only ${n} posts chosen.`),
      pick: "To pick specific posts, open the rule “Comment Studio · preguntas de precio y hora” in Automations.",
      open: "Open Automations",
    },
    keywords: {
      title: "Words",
      description: "Answers only when the comment contains one of these words.",
      placeholder: "Type a word and press Enter",
      reset: "Back to the suggested ones",
      count: (n: number, max: number) => `${n} of ${max}`,
      rejected: {
        empty: "Type something.",
        tooLong: "At most 50 characters per word.",
        duplicate: "That word is already there.",
        tooMany: "At most 50 words.",
      },
    },
    publicReply: {
      title: "Public reply",
      description: "What everyone sees under the comment.",
      switch: "Reply publicly",
    },
    direct: {
      title: "Direct",
      description: "The private message the commenter receives. Built from your services and prices in the Knowledge Base; edit it if you like.",
      useGenerated: "Use the suggested text",
    },
    problems: {
      posts: "The rule is set to chosen posts but the list is empty: check it in Automations.",
      keywords: "Add at least one word.",
      public: "Write the public reply or turn it off.",
      direct: "Write the Direct message.",
    },
    action: { turnOn: "Turn on", save: "Save changes", repair: "Repair", switch: "Switch to Comment Studio", working: "Saving…" },
    toast: {
      saved: "Done: Comment Studio is on.",
      failed: "Could not save.",
      readback: "Saved, but the bot did not end up as expected. Check Automations.",
    },
    errors: {
      InstagramNotConnected: "Connect your Instagram in Channels and try again.",
      InstagramDoesNotConnected: "Connect your Instagram in Channels and try again.",
      FuelyListOfPostsNoConnectedAccount: "Connect your Instagram in Channels and try again.",
      FuelyAutomationBeingEdited: "Someone is editing the automations right now. Wait a moment and try again.",
      FuelyAutomationScopeLimitReached: "This bot already has the maximum number of comment rules. Delete one in Automations.",
      FuelyKeywordsTooMany: "Too many words: keep at most 50.",
      FuelyKeywordTooLong: "A word is longer than 50 characters.",
    },
  },
  pt: {
    title: "Comment Studio",
    subtitle: "Cada comentário com intenção de compra recebe um Direct com seus preços. Sem IA, sem custo por uso.",
    language: "Idioma",
    loading: "Lendo seu bot…",
    loadFailed: "Não foi possível ler as automações.",
    retry: "Tentar de novo",
    status: { loading: "…", running: "Ativo", off: "Desligado", drifted: "Precisa de reparo", aiBooking: "Assistente com IA ativo" },
    statusHint: {
      running: "Responde os comentários com suas palavras e envia o Direct.",
      off: "Ainda não responde comentários. Revise os textos e ligue.",
      drifted: "Alguém mudou as automações à mão. Repare com um toque.",
      aiBooking: "O assistente com IA cuida do Direct. Mudar para o Comment Studio desliga a IA e deixa só respostas fixas.",
    },
    instagram: {
      missing: "Conecte seu Instagram",
      missingHint: "O Comment Studio responde na conta conectada em Canais.",
      connect: "Ir para Canais",
      connected: (handle: string) => `Responde em @${handle}`,
    },
    facts: {
      unavailable: "Não foi possível ler seus serviços e horários; os textos sugeridos são genéricos.",
    },
    posts: {
      title: "Publicações",
      description: "Onde ele escuta os comentários.",
      all: "Todas as publicações.",
      selectedHint: (n: number) => (n === 1 ? "Só 1 publicação escolhida." : `Só ${n} publicações escolhidas.`),
      pick: "Para escolher publicações específicas, abra a regra “Comment Studio · preguntas de precio y hora” em Automações.",
      open: "Abrir Automações",
    },
    keywords: {
      title: "Palavras",
      description: "Responde só se o comentário contiver uma destas palavras.",
      placeholder: "Digite uma palavra e Enter",
      reset: "Voltar às sugeridas",
      count: (n: number, max: number) => `${n} de ${max}`,
      rejected: {
        empty: "Digite algo.",
        tooLong: "No máximo 50 caracteres por palavra.",
        duplicate: "Essa palavra já está na lista.",
        tooMany: "No máximo 50 palavras.",
      },
    },
    publicReply: {
      title: "Resposta pública",
      description: "O que todo mundo vê embaixo do comentário.",
      switch: "Responder em público",
    },
    direct: {
      title: "Direct",
      description: "A mensagem privada que quem comentou recebe. Montada com seus serviços e preços da base de conhecimento; edite se quiser.",
      useGenerated: "Usar o texto sugerido",
    },
    problems: {
      posts: "A regra está com publicações escolhidas, mas a lista está vazia: confira em Automações.",
      keywords: "Adicione pelo menos uma palavra.",
      public: "Escreva a resposta pública ou desligue-a.",
      direct: "Escreva a mensagem do Direct.",
    },
    action: { turnOn: "Ligar", save: "Salvar alterações", repair: "Reparar", switch: "Mudar para o Comment Studio", working: "Salvando…" },
    toast: {
      saved: "Pronto: o Comment Studio está ativo.",
      failed: "Não foi possível salvar.",
      readback: "Salvou, mas o bot não ficou como esperado. Confira em Automações.",
    },
    errors: {
      InstagramNotConnected: "Conecte seu Instagram em Canais e tente de novo.",
      InstagramDoesNotConnected: "Conecte seu Instagram em Canais e tente de novo.",
      FuelyListOfPostsNoConnectedAccount: "Conecte seu Instagram em Canais e tente de novo.",
      FuelyAutomationBeingEdited: "Alguém está editando as automações agora. Espere um momento e tente de novo.",
      FuelyAutomationScopeLimitReached: "Este bot já tem o máximo de regras para comentários. Apague uma em Automações.",
      FuelyKeywordsTooMany: "Palavras demais: deixe no máximo 50.",
      FuelyKeywordTooLong: "Uma palavra passa de 50 caracteres.",
    },
  },
});
